# Generated by Django 2.2.3 on 2019-07-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SOA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='arash',
            options={'verbose_name_plural': 'arashes'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='arash',
        ),
        migrations.AddField(
            model_name='arash',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arashes',
                                    to='SOA.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='alley',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='details',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='fax',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='arash',
            name='license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arash',
                                       to='SOA.License'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company',
                                       to='SOA.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users',
                                    to='SOA.Address'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(max_length=256)),
                ('solve', models.TextField(max_length=256)),
                ('request_date', models.DateTimeField()),
                ('solve_date', models.DateTimeField()),
                ('arash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests',
                                            to='SOA.Arash')),
                ('user', models.ManyToManyField(related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
