# Generated by Django 2.2.3 on 2019-07-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('SOA', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fields',
            field=models.TextField(null=True),
        ),
    ]
